{
 "title": "PgStatActivityHistory",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Session Utilization",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, simplified_query, count(*) as total\nFROM \"default\".\"pg_stat_activity_history\"\nWHERE ( time >= $__fromTime AND time <= $__toTime )\nGROUP BY simplified_query, time ORDER BY time ASC, simplified_query ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Session Utilization",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, simplified_query, count(*) as total\nFROM \"default\".\"pg_stat_activity_history\"\nWHERE ( time >= $__fromTime AND time <= $__toTime )\nGROUP BY simplified_query, time ORDER BY time ASC, simplified_query ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, simplified_query, count(*) as total\nFROM \"default\".\"pg_stat_activity_history\"\nWHERE ( time >= $__fromTime AND time <= $__toTime AND wait_event_type IS NULL)\nGROUP BY simplified_query, time ORDER BY time ASC, simplified_query ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, simplified_query, count(*) as total\nFROM \"default\".\"pg_stat_activity_history\"\nWHERE ( time >= $__fromTime AND time <= $__toTime AND wait_event_type IS NULL )\nGROUP BY simplified_query, time ORDER BY time ASC, simplified_query ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Long Transactions (5ms)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, simplified_query, count(*) as total\nFROM \"default\".\"pg_stat_activity_history\"\nWHERE ( time >= $__fromTime AND time <= $__toTime AND date_diff('milliseconds', timestamp, xact_start) > 5)\nGROUP BY simplified_query, time ORDER BY time ASC, simplified_query ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Long Running Transactions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, simplified_query, count(*) as total\nFROM \"default\".\"pg_stat_activity_history\"\nWHERE ( time >= $__fromTime AND time <= $__toTime AND date_diff('milliseconds', timestamp, xact_start) > 5)\nGROUP BY simplified_query, time ORDER BY time ASC, simplified_query ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "WIP: Locks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, simplified_query, locktype, count(*) as total\nFROM \"default\".\"pg_stat_activity_history\"\nWHERE ( time >= $__fromTime AND time <= $__toTime  AND locktype IS NOT null )\nGROUP BY simplified_query, locktype, time ORDER BY time ASC, simplified_query ASC LIMIT 1000"
    }
   ]
  }
 ]
}