version: "2"

services:
  postgres_dev:
    image: postgres:16
    hostname: localhost
    ports:
      - "5432:5432"
    command: >
      postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c track_activity_query_size=2048
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

  postgres_test:
    image: postgres:16
    hostname: localhost
    ports:
      - "5431:5432"
    command: >
      postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c track_activity_query_size=2048
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

  redis:
    image: redis:latest
    hostname: localhost
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  clickhouse_dev:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: clickhouse_dev
    hostname: clickhouse
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"

  clickhouse_test:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: clickhouse_test
    hostname: clickhouse
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8124:8123"
      - "127.0.0.1:9001:9000"
  grafana:
    build:
      context: ${PWD}/docker_files/
      dockerfile: grafana.Dockerfile
    container_name: grafana
    hostname: grafana
    volumes:
      - ${PWD}/fs/volumes/grafana/etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ${PWD}/fs/volumes/grafana/etc/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ${PWD}/fs/volumes/grafana/etc/dashboards:/etc/dashboards
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - clickhouse_dev
