default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 5
      preserve_finished_jobs: false
      recurring_tasks:
        pg_monitor:
          class: PgMonitorJob
          schedule: every 10 seconds
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 0.1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
